name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run_job:
        type: Boolean
        required: false
        description: "Run Specific Job"
      custom_message:
        type: String
        required: false
        description: "Enter a custom message"
     

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:

      - run: echo "Exploring Workflow Dispatch Trigger"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Custom Message
        run:
          echo "${{github.event.inputs.custom_message}}"
    
